base_prompt = "(masterpiece,best quality,high quality,highres,ultra-detailed),looking at viewer,({}:1.2)"
light_prompt = "(uniform lighting on the face,soft lighting,sun ray:1.2),(expansive:1.4)"
negative_prompt = {
    "normal": "NSFW,(worst quality,low quality,normal quality,badhandv4,ng_deepnegative_v1_75t,open mouth,teeth,thick lips,:1.2),lowres,watermark,Blurred eyes,naked,nude",
    "no_glasses": "NSFW,(worst quality,low quality,normal quality,badhandv4,ng_deepnegative_v1_75t,open mouth,teeth,thick lips,:1.2),lowres,watermark,Blurred eyes,naked,nude,glasses",
}
background_prompt = {
    "beach_girl": "A tropical paradise with crystal-clear waters,white sandy beaches,tall palm trees swaying in the breeze",
    "sky_dancer": "A tranquil beach at midnight with a shimmering ocean under the starry sky,The moonlight softly illuminates the scene",
    "spring_garden": "A lush garden with blooming cherry blossoms,a winding stone path leading to a vintage wooden bench,butterflies flying around",
    "office_professional": "A modern office space with a sleek wooden desk, state-of-the-art laptop open with financial charts, a wall clock showing it's nearly end-of-day, and a small potted succulent plant",
    "urban_nightlife": "A bustling city street illuminated by neon lights from billboards, towering skyscrapers in the background, cars and people passing by",
    "autumnal_cafe": "A cozy coffee shop with exposed brick walls, wooden tables, and a chalkboard menu, a large window shows falling autumn leaves outside",
    "comic_excitement": "A bustling convention hall filled with colorful booths, cosplayers and merchandise, large banners showcasing comic book and anime characters",
    "rainy_night_bookstore": "A dimly lit independent bookstore, raindrops trickling down a window, shelves filled with ancient and new books, a soft glow from table lamps",
    "winter_ski": "A snowy mountain slope with ski lifts and pine trees, bright blue skies, and freshly laid ski tracks",
    "museum_adventure": "Classic museum setting with marble pillars, various art pieces, and sculptures, spotlights illuminating important exhibits",
    "rainforest_expedition": "Lush tropical foliage, a flowing waterfall in the background, colorful birds and exotic plants",
    "space_exploration": "A spaceship cockpit with high-tech controls, windows showing the vastness of outer space and distant planets",
    "racetrack_glamour": "A bustling racetrack with fast cars zooming by, pit crew in action, grandstand filled with spectators",
    "farm_life": "A scenic farm with crops, barns, and farm animals like cows and chickens, perhaps a tractor in the distance",
    "romantic_wedding": "A beautiful wedding venue, perhaps a garden or a beach, adorned with flowers, ribbons, and a beautifully set altar",
    "traveling_historian": "An ancient library with dusty scrolls, faded maps, and mysterious artifacts, or possibly a futuristic archive with holographic displays",
    "music_festival": "An open-air stage with bright lights and speakers, a crowd of festival-goers, and multiple food and merchandise stalls",
    "school_life": "A typical classroom with desks, a blackboard, and educational posters, students and a teacher in the background",
    "japanese_anime": "A vibrant school setting with cherry blossom trees, a school building in the background, and perhaps a glimpse of a sports festival or cultural fair",
    "lazy_homeday": "A cozy living room or bedroom setting with plush cushions, soft blankets and a bookshelf, a cup of coffee or tea on a side table,a pet lounging nearby",
    "sexy_girl": "An intimate setting, perhaps a dimly lit room with velvet curtains, candlelight, or a rooftop bar at night with city lights in the background",
    "id_photo": "ID photo,simple background",
}
clothing_prompt = {
    "beach_girl": "A colorful bikini paired with a sheer beach cover-up,A wide-brimmed hat,flip-flops on the feet",
    "sky_dancer": "An elegant,flowing dress in midnight blue,adorned with small,glittering stars,Wearing a simple silver tiara and matching star-shaped earrings",
    "spring_garden": "A knee-length floral dress with a pastel color palette,a straw hat adorned with a silk ribbon, delicate lace gloves that reach the wrists",
    "office_professional": "A tailored charcoal gray business suit with a crisp white shirt, black leather dress shoes, and a matching leather briefcase",
    "urban_nightlife": "A sleek black leather jacket, skinny jeans that sit well on the hips, and high-heeled boots with metallic accents",
    "autumnal_cafe": "A chunky knit sweater in earthy tones, high-waisted jeans, and ankle boots, accessorized with a scarf and a book under the arm",
    "comic_excitement": "A detailed cosplay outfit representing a favorite superhero or anime character, complete with props like a shield or wand",
    "rainy_night_bookstore": "A casual but stylish ensemble consisting of a turtleneck, a long trench coat, and knee-high leather boots",
    "winter_ski": "A colorful, insulated ski suit, matching ski gloves, and a pair of stylish ski goggles",
    "museum_adventure": "A chic yet comfortable outfit: a blazer over a casual shirt, tailored trousers, and loafers, perhaps holding an exhibit guide",
    "rainforest_expedition": "Quick-dry shirt and cargo shorts, hiking boots, and a wide-brimmed hat, equipped with a backpack and binoculars",
    "space_exploration": "A futuristic space suit with intricate detailing, gloves with touch-sensitive pads, and a helmet under the arm",
    "racetrack_glamour": "A racing jumpsuit complete with sponsor patches, racing gloves, and sturdy boots, perhaps a helmet under the arm",
    "farm_life": "Durable jeans, a plaid shirt, and sturdy boots, accessorized with a handkerchief and perhaps carrying a pail or gardening tools",
    "romantic_wedding": "A stunning wedding dress with lace details, a long flowing veil, and pearl accessories, groom in a classic tuxedo",
    "traveling_historian": "A blend of vintage and futuristic clothing: a waistcoat with intricate patterns, a modern utility belt filled with time-travel gadgets",
    "music_festival": "A boho-chic outfit with a fringed vest, denim shorts, and leather boots, accessorized with layered necklaces and flower crowns",
    "school_life": "A school uniform or casual clothes suitable for school, accessorized with a backpack and maybe some quirky pins or patches",
    "japanese_anime": "Japanese sailor dress",
    "lazy_homeday": "Casual and comfortable loungewear like oversized sweatshirts, yoga pants or pajama bottoms, paired with fuzzy socks or slippers",
    "sexy_girl": "A form-fitting dress or top highlighting the silhouette, paired with high heels; accessorized with delicate jewelry like a choker or drop earrings",
    "id_photo": "formal wear",
}
hair_prompt = {
    "beach_girl": "Natural beachy waves with sun-kissed highlights,complemented by a wide-brimmed sun hat",
    "sky_dancer": "Hair pulled back into a simple ponytail or under a beanie hat, functional and practical",
    "spring_garden": "Long wavy hair gently resting on the shoulders,adorned with a delicate flower hairpin near the ear",
    "office_professional": "Hair slicked back in a professional manner, a clean shave that enhances the jawline",
    "urban_nightlife": "Short and spiky hair with streaks of bold colors like pink or blue, adding a sense of rebelliousness",
    "autumnal_cafe": "A messy bun secured with a tortoiseshell hairpin, loose strands framing the face",
    "comic_excitement": "A wig styled to match the character being cosplayed, perhaps with exaggerated spikes or elaborate braids",
    "rainy_night_bookstore": "Loose waves tucked under a stylish beret, lending an air of sophistication",
    "winter_ski": "Hair tucked into a warm, knitted beanie, small wisps of hair peeking out",
    "museum_adventure": "A sleek, low ponytail or chignon for a polished look, or a fashionable headband",
    "rainforest_expedition": "Hair in a tight, practical braid or under a hat, to keep it out of the way during the expedition",
    "space_exploration": "Hair in a high bun or tight ponytail to fit inside the helmet, or shaved short for practicality",
    "racetrack_glamour": "Hair styled in a short bob or pulled back into a sleek ponytail, suitable for fitting under a helmet",
    "farm_life": "Hair tied in a bandana or a simple hat to protect from the sun, styled in a practical bun or ponytail",
    "romantic_wedding": "A sophisticated updo adorned with small flowers or jeweled hairpins, or flowing locks styled in romantic waves",
    "traveling_historian": "Hair styled in a loose braid or ponytail, adorned with a few trinkets or ornaments that represent different eras",
    "music_festival": "Hair styled in loose curls or braids, maybe with some temporary color streaks or glitter",
    "school_life": "A simple and functional hairstyle like a ponytail or a short bob, possibly adorned with a ribbon or a headband",
    "japanese_anime": "Anime-styled hair with exaggerated spikes or flowing locks, possibly with highlights or unusual colors like blue or pink",
    "lazy_homeday": "Hair in a relaxed, messy bun or just flowing freely, perhaps a few strands framing the face for an effortless look",
    "sexy_girl": "Voluminous waves or sleek straight hair, possibly with a side part or a seductive fringe over one eye",
    "id_photo": "Hair tied up,ears exposed",
}
posing_prompt = {
    "beach_girl": "Reclining on a sun lounger,looking relaxed and happy,with the sea as the perfect backdrop",
    "sky_dancer": "Dancing gracefully on the wet sand,A serene and dreamy expression on the face",
    "spring_garden": "A serene expression on the face while smelling a freshly picked cherry blossom,eyes closed and a slight smile",
    "office_professional": "",
    "urban_nightlife": "a smirk on the face, looking as if they own the night",
    "autumnal_cafe": "an engrossed expression, intermittently sipping on a pumpkin spice latte",
    "comic_excitement": "a face full of excitement and enthusiasm",
    "rainy_night_bookstore": "gazing out the rain-soaked window with a contemplative expression",
    "winter_ski": "an expression of thrill and anticipation",
    "museum_adventure": "a look of fascination and intellectual curiosity",
    "rainforest_expedition": "an expression of awe and wonder",
    "space_exploration": "a look of focus and determination",
    "racetrack_glamour": "a look of fierce determination and focus",
    "farm_life": "a look of contentment and hard work",
    "romantic_wedding": "with joy and love",
    "traveling_historian": "an expression of fascination and curiosity",
    "music_festival": "Dancing to the music or singing along, an expression of pure enjoyment and freedom",
    "school_life": "Engaged in classroom activities like answering a question or taking notes, an expression of focus and interest",
    "japanese_anime": "Engaged in typical anime school life activities",
    "lazy_homeday": "simply lounging on the sofa, an expression of ultimate relaxation and contentment",
    "sexy_girl": "A confident gaze directed at the viewer or looking over the shoulder, a subtle smirk or biting the lip; radiating self-assurance and allure",
    "id_photo": "",
}

adtailer_face_prompt = "{},looking at viewer,(masterpiece,best quality,high quality,highres,ultra-detailed)"
adtailer_face_negative_prompt = {
    "normal": "NSFW,(worst quality,low quality,normal quality,ng_deepnegative_v1_75t:1.5),thick lips,lowres,watermark,Blurred eyes",
    "no_glasses": "NSFW,(worst quality,low quality,normal quality,ng_deepnegative_v1_75t:1.5),thick lips,lowres,watermark,Blurred eyes,glasses",
}
adtailer_hand_prompt = "{} hand,(masterpiece, best quality, high quality, highres, ultra-detailed)"
adtailer_hand_negative_prompt = "NSFW,(worst quality,low quality,normal quality,badhandv4:1.5),lowres,watermark"
